[package]
name = "nes-step"
version = "0.1.0"
edition = "2024"

[dependencies]
nes-core = { path = "../nes-core" , features = ["testing-utils"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"