[package]
name = "nes-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.0"
once_cell = "1.21.1"
blip_buf = "0.1.6"
thiserror = "2.0.17"

[features]
default = []
tracing = []
testing-utils = []
runtime-ppu-schedule = []
linear-apu-approximation = []